CREATE TABLE IF NOT EXISTS `VGDPlayer` (`id` UUID NOT NULL, `name` VARCHAR(16) NOT NULL, `groupId` BIGINT, PRIMARY KEY (`id`));

CREATE TABLE IF NOT EXISTS `VGDGroup`(`id` BIGINT AUTO_INCREMENT NOT NULL, `name` VARCHAR(255) NOT NULL, `owner` UUID NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`owner`) REFERENCES `VGDPlayer` (`id`) ON DELETE RESTRICT);

ALTER TABLE `VGDPlayer` ADD FOREIGN KEY (`groupId`) REFERENCES `VGDGroup` (`id`) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS `VGDCuredVillager` (`id` UUID NOT NULL, `reputationValue` INT NOT NULL, `curerId` UUID NOT NULL, `groupId` BIGINT, PRIMARY KEY (`id`), FOREIGN KEY (`curerId`) REFERENCES `VGDPlayer` (`id`) ON DELETE CASCADE, FOREIGN KEY (`groupId`) REFERENCES `VGDGroup` (`id`) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS `VGDGroupInvite` (`id` BIGINT AUTO_INCREMENT NOT NULL, `accepted` BOOLEAN NOT NULL, `declined` BOOLEAN NOT NULL, `createdAt` TIMESTAMP NOT NULL, `minutesTillExpires` INT NOT NULL, `inviterId` UUID NOT NULL, `inviteeId` UUID NOT NULL, `groupId` BIGINT NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`inviterId`) REFERENCES `VGDPlayer` (`id`) ON DELETE CASCADE, FOREIGN KEY (`inviteeId`) REFERENCES `VGDPlayer` (`id`) ON DELETE CASCADE, FOREIGN KEY (`groupId`) REFERENCES `VGDGroup` (`id`) ON DELETE CASCADE);
